# Funciones lineales

In [108]:
import numpy as np

In [109]:
def f(x):
    return np.sum(x)

In [110]:
print('f(0) = ', f(np.array((0,0,0,0))))

f(0) =  0


In [111]:
print('f([1,0,0,0]) = ', f(np.array((1,0,0,0))))

f([1,0,0,0]) =  1


In [112]:
print('f([1,1,1,1]) = ', f(np.array((1,1,1,1))))

f([1,1,1,1]) =  4


In [113]:
def g(x):
    return x[0]

In [114]:
print('g(0) = ', g(np.array((0,0,0,0))))

g(0) =  0


In [115]:
print('g([0,0,1]) = ', g(np.array((0,0,1))))

g([0,0,1]) =  0


In [116]:
print('g([1,0,4]) = ', g(np.array((1,0,4))))

g([1,0,4]) =  1


## Comprobación de superposición y linealidad

* Función f(x)

In [117]:
a = np.array((1,1,1,1))
b = np.array((1,0,1,0))
x,y = 1,-2

In [118]:
x*a + y*b

array([-1,  1, -1,  1])

In [119]:
print('f(x*a +y*b) = ', f(x*a + y*b))

f(x*a +y*b) =  0


In [120]:
print('x*f(a) +y*f(b) = ', x*f(a)+y*f(b))

x*f(a) +y*f(b) =  0


* Función g(x)

In [121]:
print('g(x*a +y*b) = ', g(x*a + y*b))

g(x*a +y*b) =  -1


In [122]:
print('x*g(a) +y*g(b) = ', x*g(a)+y*g(b))

x*g(a) +y*g(b) =  -1


## Teorema de funciones lineales

In [123]:
def MAX(x):
    return np.max(x)

In [124]:
print('MAX([1,0,2]) = ', MAX(np.array((1,0,2))))

MAX([1,0,2]) =  2


In [125]:
x = np.array((1,-1))
y = np.array((-1,1))
a = b = 1/2

In [126]:
print('MAX(a*x + b*y) = ', MAX(a*x + b*y))

MAX(a*x + b*y) =  0.0


In [127]:
print('a*MAX(Z) + b*MAX(y) = ', a*MAX(x) + b*MAX(y))

a*MAX(Z) + b*MAX(y) =  1.0


## Ejercicio: Determina si las siguientes funciones son lineales o no

* $f(\mathbf{x}) = x_{n-1} - x_{0}$

* Si $\mathbf{x}\in\mathbb{R}^{4}$ y $f:\mathbb{R}^{4} \to \mathbb{R}$ definida como $f(\mathbf{x})=x_{3}+(x_{3}-x_{2})$

In [149]:
x = np.random.rand(np.random.randint(100))
y = np.random.rand(x.size)
a = 10
b = 42

def f1(vector):
    return vector[-1] - vector[0]

In [150]:
print('Function(a*x + b*y) = ', f1(a*x + b*y))
print('a*Function(x) + b*Function(y) = ', a*f1(x) + b*f1(y))
# La función es lineal

Function(a*x + b*y) =  12.07195451035642
a*Function(x) + b*Function(y) =  12.071954510356413


In [151]:
x = np.random.rand(4)
y = np.random.rand(4)
a = np.random.randint(100)
b = np.random.randint(100)

def f2(vector):
    return vector[2] + (vector[2]-vector[1])

In [152]:
print('Function(a*x + b*y) = ', f2(a*x + b*y))
print('a*Function(x) + b*Function(y) = ', a*f2(x) + b*f2(y))
# La función es lineal

Function(a*x + b*y) =  63.17517839159804
a*Function(x) + b*Function(y) =  63.17517839159803


## Problema: Potencia en un clúster de procesadores y temperatura

In [132]:
# Datos
P1 = np.array([10,10,10])
P2 = np.array([100,10,10])
P3 = np.array([10,100,10])
P4 = np.array([10,10,100])
T1 = 35
T2 = 60
T3 = 75
T4 = 65

In [133]:
# Sitema de ecuaciones lineales mediante matrices
# P matriz de coeficientes, 3 primeros números vector a y ultimo número valor del bias b

P = np.array(
[[10, 10, 10, 1],
[100,10,10, 1],
[10,100,10, 1],
[10, 10, 100, 1]])
T = np.array([T1, T2,T3, T4])

In [134]:
a = np.linalg.solve(P,T)[0:3]
b = np.linalg.solve(P,T)[3]
a, b
# (array([0.27777778, 0.44444444, 0.33333333]), 24.444444444444443)

(array([0.27777778, 0.44444444, 0.33333333]), 24.444444444444443)

In [135]:
def temperature(P):
    return a.T@P+b
T1_solution = temperature(P1)
T2_solution = temperature(P2)
T3_solution = temperature(P3)
T4_solution = temperature(P4)

T_solution = np.array((T1_solution,T2_solution,T3_solution,T4_solution))
T_solution
# array([35., 60., 75., 65.])

array([35., 60., 75., 65.])

In [136]:
# Solución mediante lstsq
np.linalg.lstsq(P,T,rcond=None)[0]
# array([ 0.27777778,  0.44444444,  0.33333333, 24.44444444])

array([ 0.27777778,  0.44444444,  0.33333333, 24.44444444])

* Temperatura máxima

In [137]:
# Temperatura a máxima potencia
T_máxima = temperature([100,100,100])
T_máxima
# 130.0

130.0

In [138]:
# La temperatua máxima que se puede alcanzar es de 130

* Potencia para que los procesadores alcancen una temperatura de 150

In [139]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [140]:
T = T.reshape(-1,1)

In [141]:
model.fit(T,P)

LinearRegression()

In [142]:
print("coeff: ", *model.coef_)
print("intercept: ", model.intercept_)
# coeff:  [0.1294964] [1.68345324] [0.64748201] [0.]
# intercept:  [ 24.89208633 -66.4028777   -5.53956835   1.        ]

# Pares x + b, para cada una de las 4 salidas

coeff:  [0.1294964] [1.68345324] [0.64748201] [0.]
intercept:  [ 24.89208633 -66.4028777   -5.53956835   1.        ]


In [143]:
P_150 = model.predict([[150]])[0][:-1]
P_150 
# array([ 44.31654676, 186.11510791,  91.58273381])

array([ 44.31654676, 186.11510791,  91.58273381])

In [144]:
# Comprobación de temperatura con el vector de la potencia encontrada de los procesadores
T_150 = temperature(P_150)
T_150

150.0

* ¿Cuál es la potencia minima para alcanzar 150 de Temperatura?

In [145]:
P = 100
T = temperature([P,P,P])

while (T < 150):
    tol = 0.0001
    P += tol
    T = temperature([P,P,P])
print(P,T)
# 118.94740000062899 150.00003333399727

118.94740000062899 150.00003333399727


Solución mediante busqueda binaria

In [146]:
tol = 0.0001
min_P = 100
max_P = 125

P = np.array([min_P,min_P,min_P])

while (abs(temperature(P) - 150) > tol):

    avg_P = np.mean([min_P,max_P])
    P = np.array([avg_P,avg_P,avg_P])
    T = temperature(P)

    if T > 150:
        max_P =  avg_P
    else:
        min_P =  avg_P

print(P,T)

# [118.94683838 118.94683838 118.94683838] 149.9994405110677

[118.94741058 118.94741058 118.94741058] 150.00004450480142
