# Producto interno (escalar o punto)

In [915]:
import numpy as np

In [916]:
a = np.array([1,0,0,0]) #declaramos el vector e_1

b = np.array([0,0,1,0]) #declaramos el vector e_2

In [917]:
print('<a,b> =',np.dot(a,b))

<a,b> = 0


In [918]:
print('<a,b> =',a.T@b)

<a,b> = 0


## Evaluación de poliomios

In [919]:
def p(x):
    return np.array([1,2])@np.array([1,x])

In [920]:
print('p(0) = ',p(0))
print('p(1) = ',p(1))
print('p(2) = ',p(2))

p(0) =  1
p(1) =  3
p(2) =  5


# Ejercicios

## Problema 1: Análisis de sentimiento de tweets

In [921]:
# Tweets
A = "Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!"
B ="Vaya señora que bueno que se asesora por alguien inteligente no por el ignorante del Gatt."
C =  "Se me ocurre y sin ver todos los videos de Plazti que me informéis por dónde empiezo. Entiendo que os tendría que decir quién soy y que quiero, vamos conocerme para asesorarme bien. Un saludo"
D = "Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!"
TWEETS = (A,B,C,D)

In [922]:
PST_WORDS = ("excelente","gran","quiero","positivo",'bien','positivo','bueno','inteligente')

NTR_WORDS = ("pérdida",'aprender','estudio','platzi')

NGT_WORDS = ("muerte","luto",'ignorante')

PST_WORDS = tuple(set(PST_WORDS))
NTR_WORDS = tuple(set(NTR_WORDS))
NGT_WORDS = tuple(set(NGT_WORDS))
WORDS = PST_WORDS + NGT_WORDS + NTR_WORDS

In [923]:
def normalize_tweets(tweets: tuple) -> list:
    tweets_list = []
    for tweet in tweets:
        for i in "!().,":
            tweet = tweet.replace(i,"")
            tweet = tweet.lower()
        list_tweet = tweet.split()
        tweets_list.append(list_tweet)
    return tweets_list

In [924]:
tweets_list = normalize_tweets(TWEETS)

In [925]:
from collections import Counter

In [926]:
def counting_words(words: tuple, tweets_list: list) -> list:
    counted_words_list = []
    counted_words_vector = []

    for i in tweets_list:
        cw_dict = {}
        all_words_dict = Counter(i)

        for word in words:
            cw_dict[word] = all_words_dict.get(word,0)

        counted_words_list.append(cw_dict)
        counted_words_vector.append(list(cw_dict.values()))

    return counted_words_list, np.array(counted_words_vector)


In [927]:
counted_words, w_vectors = counting_words(WORDS, tweets_list)
w_vectors
# array([[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
#        [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
#        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]])

array([[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]])

In [928]:
def classified_vectors(counted_words:list, pst_words:tuple, ngt_words:tuple, ntr_words:tuple) -> list:
    classified_vector = []

    for cw_dict in words_counted:
        temp_list = [0,0,0]
        for word in pst_words:
            temp_list[0] += cw_dict.get(word,0)
        for word in ngt_words:
            temp_list[1] += cw_dict.get(word,0)
        for word in ntr_words:
            temp_list[2] += cw_dict.get(word,0)
        classified_vector.append(temp_list)

    return np.array(classified_vector)


In [929]:
s_vectors = classified_vectors(counted_words, PST_WORDS, NGT_WORDS, NTR_WORDS)
s_vectors

# array([[2, 2, 0],
#        [2, 1, 0],
#        [2, 0, 0],
#        [1, 0, 1]])

array([[2, 2, 0],
       [2, 1, 0],
       [2, 0, 0],
       [1, 0, 1]])

In [930]:
def avgs_vectors(vectors):
    avgs = []
    for i in vectors:
        avg_i = (np.ones(i.size) / i.size).T@i
        avgs.append(avg_i)
    return np.array(avgs)
    


In [931]:
avgs_w = avgs_vectors(w_vectors) 
avgs_s = avgs_vectors(s_vectors) 
avgs_w, avgs_s
# (array([0.28571429, 0.21428571, 0.14285714, 0.14285714]),
#  array([1.33333333, 1.        , 0.66666667, 0.66666667]))


(array([0.28571429, 0.21428571, 0.14285714, 0.14285714]),
 array([1.33333333, 1.        , 0.66666667, 0.66666667]))

In [932]:
def Pro_s(vectors):
    avgs = []
    for i in vectors:
        avg_i = i / np.sum(i)
        avgs.append(avg_i)
    return np.array(avgs)

In [933]:
P_s = Pro_s(s_vectors)
P_s
P_s_T=P_s.T
print(P_s)
# [[0.5        0.5        0.        ]
#  [0.66666667 0.33333333 0.        ]
#  [1.         0.         0.        ]
#  [0.5        0.         0.5       ]]

[[0.5        0.5        0.        ]
 [0.66666667 0.33333333 0.        ]
 [1.         0.         0.        ]
 [0.5        0.         0.5       ]]


In [934]:
def score(s_vectors):
    scores = []
    for s in s_vectors:
        score = np.array((1, 0, -1)).dot(s)
        scores.append(score)
    return np.array(scores)

In [935]:
scores = score(s_vectors)
scores
#array([2, 2, 2, 0])

array([2, 2, 2, 0])

In [936]:
# Tweet más positivo
TWEETS[np.argmax(scores)]

# 'Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!'

'Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!'

In [937]:
# Tweet más negativo
TWEETS[np.argmin(scores)]
# 'Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!'

'Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!'

In [938]:
# Calidad promedio
np.mean(scores)
"1.5"

'1.5'

In [939]:
#Interpretación de avg(s) y score(s)

#avg(s) te permite identificar la cantidad de palabras encontradas que se pudieron clasificar, un bajo promedio siginifica que no se encontraron palabras por lo que el modelo es menos preciso y un mayor promedio indica mayor precisión.

#score(s) te permite saber si un tweet contiene más palabras, positivas,negativas o neutras dependiendo su valor. Mayor score indica más palabar positivas, menor score palabras negativas y valor cercano a 0 significa que las palabras estan balanceadas.

In [940]:
#Relacion de la calidad con socre(s) y avg(s)

# A mayor calidad, tendremos más datos para confirmar que tanto el score como el avg son correctos, con poca calidad los datos del score y avg son poco representativos.

In [941]:
result = {"Tweet":TWEETS, "Calidad(w)":avgs_w, "Calidad(s)":avgs_s, "P+":P_s_T[0],"Pn":P_s_T[2],
"P-":P_s_T[1], "Score":scores}

In [942]:
import pandas as pd 
df = pd.DataFrame(result)

In [944]:
df
# Tweet	Calidad(w)	Calidad(s)	P+	Pn	P-	Score
# 0	Gran mexicano y excelente en su área, su muert...	0.285714	1.333333	0.500000	0.0	0.500000	2
# 1	Vaya señora que bueno que se asesora por algui...	0.214286	1.000000	0.666667	0.0	0.333333	2
# 2	Se me ocurre y sin ver todos los videos de Pla...	0.142857	0.666667	1.000000	0.0	0.000000	2
# 3	Soy docente universitario, estoy intentando pr...	0.142857	0.666667	0.500000	0.5	0.000000	0

Tweet  Calidad(w)  Calidad(s)  \
0  Gran mexicano y excelente en su área, su muert...    0.285714    1.333333   
1  Vaya señora que bueno que se asesora por algui...    0.214286    1.000000   
2  Se me ocurre y sin ver todos los videos de Pla...    0.142857    0.666667   
3  Soy docente universitario, estoy intentando pr...    0.142857    0.666667   

         P+   Pn        P-  Score  
0  0.500000  0.0  0.500000      2  
1  0.666667  0.0  0.333333      2  
2  1.000000  0.0  0.000000      2  
3  0.500000  0.5  0.000000      0