# Producto por un escalar-vector

Partamos del vector $\vec{x}= (1,-1,1)$ y del escalar $a = 3.1$ entonces, realicemos las operaciones $a\vec{x}$ y $\vec{x}a$

In [209]:
import numpy as np #primero importamos numpy

In [210]:
x = np.array([1,-1,1]) #declaramos el vector x

a = 3.1 #declaramos el escalar a

In [211]:
print('ax es',a*x)

ax es [ 3.1 -3.1  3.1]


In [212]:
print('xa es',x*a)

xa es [ 3.1 -3.1  3.1]


In [213]:
b = -a
b, b+a

(-3.1, 0.0)

In [214]:
print('(b+a)x es',(b+a)*x)

(b+a)x es [ 0. -0.  0.]


In [215]:
print('xa+xb es',b*x+ x*a)

xa+xb es [0. 0. 0.]


Ahora un ejecio más $\vec{v} = (1,1)$. Si consideramos a = -1, b = 2, c = 0.1

In [216]:
v = np.array([1,1])
a = -1
b = 2
c = 0.1

In [217]:
v*a

array([-1, -1])

In [218]:
v*b

array([2, 2])

In [219]:
v*c

array([0.1, 0.1])

# Ejercicios

**Problema 1**. Escribe TODOS los vectores unitarios estándar de $\mathbb{R}^{4}$. *Hint:* son cuatro. 

In [220]:
def unit_vectors(dimensions):
    for i in range(dimensions):
        vector = np.zeros(dimensions)
        vector[i] = 1
        print(vector)
        

In [221]:
unit_vectors(4)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


**Problema 2**. Escribe tres combinaciones lineales de vectores en $\mathbb{R}^{3}$ para expresar el vector $[1,1,1]$.

In [222]:
def combinacion_lineal(escalares, vectores):
    return sum((escalares[i]*vector for i, vector in enumerate(vectores)))

In [223]:
escalar1 = np.array((1,1,1))
vectores1 = np.array(((1,0,0),(0,1,0),(0,0,1)))
escalar2 = np.array((-1,1,1))
vectores2 = np.array(((1,1,1),(1,1,1),(1,1,1)))
escalar3 = np.array((1,0,1))
vectores3 = np.array(((1/2,1/2,1/2),(0,0,0),(1/2,1/2,1/2)))

In [224]:
print(combinacion_lineal(escalar1,vectores1))
print(combinacion_lineal(escalar2,vectores2))
print(combinacion_lineal(escalar3,vectores3))

[1 1 1]
[1 1 1]
[1. 1. 1.]


Problema 3. Escribe tres combinaciones afines con vectores de  R3  donde  β0≠β1≠β2  pero que se cumpla que  β0+β1+β2=1 . HINT: Si no se te ocurre ninguna combinación para los coeficientes la ecuación  β0+β1+β2=1  tiene infinitas soluciones, puedes hacer un programa para encontrar tres.

In [225]:
a = np.linspace(0,1,3)

In [226]:
def coefs_sum1(size):
    coefs = np.random.rand(size-1)
    coefs = np.append(coefs, 1 - sum(coefs))
    return coefs

In [227]:
print(coefs_sum1(3))
print(coefs_sum1(3))
print(coefs_sum1(3))

[ 0.55670321  0.79993337 -0.35663657]
[ 0.25086611  0.81434704 -0.06521315]
[0.10531569 0.17894955 0.71573477]
