# Suma vectores en Python

In [2]:
rojo = [255,0,0]
negro = [0,0,0]

In [4]:
print(f'rojo + negro resulta en {rojo+negro}')

rojo + negro resulta en [255, 0, 0, 0, 0, 0]


## Suma de vectores con listas

In [5]:
def suma_vectores(a,b):
    return [i+j for i,j in zip(a,b)]

In [6]:
print('suma_vectores(rojo,negro) nos devuelve',suma_vectores(rojo,negro))

suma_vectores(rojo,negro) nos devuelve [255, 0, 0]


In [7]:
print('suma_vectores(verde,negro) nos devuelve',suma_vectores([0,255,0],negro))

suma_vectores(verde,negro) nos devuelve [0, 255, 0]


## Uso de nummpy

In [9]:
import numpy as np

In [10]:
rojo = np.array(rojo)
negro = np.array(negro)

In [11]:
print(type(rojo))

<class 'numpy.ndarray'>


In [12]:
print('La suma de los numpy array rojo + negro es', rojo+negro)

La suma de los numpy array rojo + negro es [255   0   0]


In [13]:
a = np.array([1,2,3,4,5]) #declaramos el arreglo/vector a

b = np.array([-1,-2,-3,-4,5]) #declaramos el arreglo/vector b

In [14]:
c = a+b

In [15]:
print('La el vector c = a+b =',c)

La el vector c = a+b = [ 0  0  0  0 10]


# Problema

Puedes ir al sitio [siguiente sitio](https://www.w3schools.com/colors/colors_rgb.asp), el sitio te permite introducir un vector del modelo RGB y te muestra el color al que corresponde.  
 
Ahora, primer confirma a qué color corresponden el vector $\vec{a} = [0,0,255]$ y así responde:
* ¿Qué color obtienes si sumas $\vec{rojo}+\vec{verde}+\vec{a}$? 
* ¿Qué color obtienes sumando $\vec{rojo}+\vec{verde}$?
* ¿Qué color obtienes sumando $\vec{negro}-\vec{a}$? ¿Tiene sentido este resultado dentro del modelo aditivo RGB?


In [16]:
a = np.array((0,0,255))
rojo = np.array((255,0,0))
verde = np.array((0,255,0))
negro = np.array((0,0,0))

 $\vec{rojo}+\vec{verde}+\vec{a}$? 

In [17]:
rojo + verde + a #Color blanco

array([255, 255, 255])

$\vec{rojo}+\vec{verde}$?

In [18]:
rojo + verde #Color Amarillo

array([255, 255,   0])

$\vec{negro}-\vec{a}$?

In [19]:
negro - a #Sin sentido

array([   0,    0, -255])